import { describe, it, expect } from 'vitest'
import {
  parseFilename,
  isAutoGeneratedName,
  generateSmartName,
  generateCategory,
  generateTags,
  generateDescription,
  analyzePdfContent
} from '../services/aiService.js'

describe('parseFilename', () => {
  it('splits filename into words', () => {
    expect(parseFilename('hello_world.png')).toEqual(['hello', 'world'])
  })

  it('removes single character words', () => {
    expect(parseFilename('a_big_file.png')).toEqual(['big', 'file'])
  })

  it('handles hyphens', () => {
    expect(parseFilename('my-file-name.jpg')).toEqual(['my', 'file', 'name'])
  })

  it('handles spaces', () => {
    expect(parseFilename('my file name.png')).toEqual(['my', 'file', 'name'])
  })

  it('lowercases everything', () => {
    expect(parseFilename('Hello_World.PNG')).toEqual(['hello', 'world'])
  })

  it('removes extension', () => {
    expect(parseFilename('test.pdf')).toEqual(['test'])
  })
})

describe('isAutoGeneratedName', () => {
  it('detects screenshot patterns', () => {
    expect(isAutoGeneratedName('Screenshot 2026-09-07 182341.png')).toBe(true)
    expect(isAutoGeneratedName('screenshot_123.png')).toBe(true)
  })

  it('detects img patterns', () => {
    expect(isAutoGeneratedName('IMG_20260831_123456.jpg')).toBe(true)
    expect(isAutoGeneratedName('img_123.png')).toBe(true)
  })

  it('detects timestamp patterns', () => {
    expect(isAutoGeneratedName('photo_2026-09-07-182341.png')).toBe(true)
  })

  it('detects untitled', () => {
    expect(isAutoGeneratedName('Untitled.png')).toBe(true)
  })

  it('detects download patterns', () => {
    expect(isAutoGeneratedName('download_123.pdf')).toBe(true)
  })

  it('returns false for meaningful names', () => {
    expect(isAutoGeneratedName('leetcode_solution.png')).toBe(false)
    expect(isAutoGeneratedName('quarterly_report.pdf')).toBe(false)
    expect(isAutoGeneratedName('my_photo.jpg')).toBe(false)
  })
})

describe('generateSmartName', () => {
  it('generates name from meaningful words', () => {
    const words = ['quarterly', 'report', 'financial', 'analysis']
    const name = generateSmartName(words, '.pdf', 'report.pdf')
    expect(name).toContain('quarterly')
    expect(name).toContain('.pdf')
  })

  it('generates timestamped name for auto-generated filenames', () => {
    const words = ['screenshot', '2026']
    const name = generateSmartName(words, '.png', 'Screenshot 2026.png')
    expect(name).toMatch(/^png_/)
    expect(name).toContain('.png')
  })

  it('limits to 4 meaningful words', () => {
    const words = ['one', 'two', 'three', 'four', 'five', 'six']
    const name = generateSmartName(words, '.jpg', 'test.jpg')
    const nameParts = name.replace('.jpg', '').split('_')
    expect(nameParts.length).toBeLessThanOrEqual(5)
  })
})

describe('generateCategory', () => {
  it('categorizes by extension when no keyword match', () => {
    expect(generateCategory(['hello'], '.pdf')).toBe('Documents')
    expect(generateCategory(['hello'], '.png')).toBe('Images')
  })

  it('categorizes by keyword match', () => {
    expect(generateCategory(['screenshot'], '.png')).toBe('Screenshots')
    expect(generateCategory(['invoice'], '.pdf')).toBe('Finance')
    expect(generateCategory(['leetcode'], '.png')).toBe('Education')
    expect(generateCategory(['code'], '.py')).toBe('Code')
  })

  it('returns Uncategorized for unknown', () => {
    expect(generateCategory(['xyznotaword'], '.xyz')).toBe('Uncategorized')
  })
})

describe('generateTags', () => {
  it('generates tags from meaningful words', () => {
    const tags = generateTags(['leetcode', 'sliding', 'window', 'solution'])
    expect(tags).toContain('leetcode')
    expect(tags).toContain('sliding')
    expect(tags).toContain('window')
  })

  it('filters stop words', () => {
    const tags = generateTags(['the', 'and', 'for', 'solution'])
    expect(tags).not.toContain('the')
    expect(tags).not.toContain('and')
    expect(tags).toContain('solution')
  })

  it('filters single character words', () => {
    const tags = generateTags(['a', 'big', 'test'])
    expect(tags).not.toContain('a')
    expect(tags).toContain('big')
  })

  it('limits to 5 tags', () => {
    const tags = generateTags(['one', 'two', 'three', 'four', 'five', 'six', 'seven'])
    expect(tags.length).toBeLessThanOrEqual(5)
  })

  it('deduplicates tags', () => {
    const tags = generateTags(['test', 'test', 'test'])
    expect(tags.length).toBe(1)
  })
})

describe('generateDescription', () => {
  it('generates description from meaningful words', () => {
    const desc = generateDescription(['leetcode', 'solution'], 'Education', '.png', 'test.png')
    expect(desc).toContain('Education')
    expect(desc).toContain('PNG')
  })

  it('generates generic description for auto-generated names', () => {
    const desc = generateDescription(['screenshot'], 'Screenshots', '.png', 'Screenshot 2026.png')
    expect(desc).toContain('PNG')
    expect(desc).toContain('screenshot')
  })
})

describe('analyzePdfContent', () => {
  it('returns default for empty text', () => {
    const result = analyzePdfContent('')
    expect(result.category).toBe('Documents')
    expect(result.tags).toContain('pdf')
    expect(result.description).toBe('PDF document file.')
    expect(result.suggestedName).toBeNull()
  })

  it('extracts category and tags from text', () => {
    const result = analyzePdfContent('leetcode sliding window solution algorithm')
    expect(result.tags.length).toBeGreaterThan(0)
    expect(result.description).toBeDefined()
  })

  it('generates suggested name from meaningful words', () => {
    const result = analyzePdfContent('quarterly financial report 2026')
    expect(result.suggestedName).toBeDefined()
  })
})
