import path from 'path'
import { fileURLToPath } from 'url'
import { readFile } from 'fs/promises'
import { PDFParse } from 'pdf-parse'
import { analyzeImageWithGemini, analyzePdfWithGemini } from './visionService.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const UPLOAD_DIR = process.env.UPLOAD_DIR || path.join(__dirname, '../../uploads')

const CATEGORY_MAP = {
  '.pdf': 'Documents',
  '.png': 'Images',
  '.jpg': 'Images',
  '.jpeg': 'Images',
  '.webp': 'Images'
}

const KEYWORD_CATEGORIES = {
  'Screenshots': ['screenshot', 'snip', 'capture', 'screen', 'snap'],
  'Photos': ['photo', 'img', 'camera', 'dcim', 'pic', 'image'],
  'Documents': ['doc', 'report', 'paper', 'file', 'document', 'form', 'letter'],
  'Work': ['work', 'office', 'meeting', 'project', 'client', 'presentation', 'pitch', 'business', 'resume', 'cv'],
  'Personal': ['personal', 'home', 'family', 'diary', 'journal', 'selfie', 'vacation', 'travel'],
  'Finance': ['invoice', 'receipt', 'bill', 'payment', 'tax', 'salary', 'expense', 'bank', 'statement'],
  'Education': ['lecture', 'notes', 'assignment', 'course', 'tutorial', 'leetcode', 'dsa', 'study', 'class', 'exam', 'certificate'],
  'Design': ['design', 'figma', 'sketch', 'mockup', 'ui', 'ux', 'wireframe', 'banner', 'logo', 'template'],
  'Code': ['code', 'script', 'dev', 'api', 'function', 'component', 'react', 'node', 'programming'],
  'Downloads': ['download', 'temp', 'tmp']
}

const IMAGE_EXTENSIONS = ['.png', '.jpg', '.jpeg', '.webp']

const GENERIC_PATTERNS = /^(screenshot|img|image|photo|pic|untitled|document|file|download|tmp|temp|capture|snap|clipboard|paste)[_\-\s]*\(?[\d]*\)?$/i
const TIMESTAMP_PATTERN = /\d{4}[-_]?\d{2}[-_]?\d{2}[-_]?\d{6}/
const AUTO_GENERATED_PATTERNS = [
  /^screenshot[_\-\s]*\d*/i,
  /^img[_\-\s]*\d*/i,
  /^image[_\-\s]*\d*/i,
  /^photo[_\-\s]*\d*/i,
  /^pic[_\-\s]*\d*/i,
  /^untitled/i,
  /^document[_\-\s]*\d*/i,
  /^download[_\-\s]*\d*/i,
  /^clipboard[_\-\s]*/i,
  /^paste[_\-\s]*/i,
  /^tmp[_\-\s]*/i,
  /^temp[_\-\s]*/i
]

export function parseFilename(filename) {
  const name = filename
    .replace(/\.[^.]+$/, '')
    .replace(/[_\-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase()

  const words = name.split(' ').filter(w => w.length > 1)
  return words
}

export function isAutoGeneratedName(filename) {
  const baseName = filename.replace(/\.[^.]+$/, '')
  if (GENERIC_PATTERNS.test(baseName)) return true
  if (TIMESTAMP_PATTERN.test(baseName)) return true
  for (const pattern of AUTO_GENERATED_PATTERNS) {
    if (pattern.test(baseName)) return true
  }
  return false
}

function detectDateInfo(words) {
  const datePatterns = {
    year: /\b(20\d{2}|19\d{2})\b/,
    month: /\b(january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\b/,
    monthNum: /\b(0?[1-9]|1[0-2])\b/,
    day: /\b(0?[1-9]|[12]\d|3[01])\b/,
    time: /\b(\d{1,2})[:\-]?(\d{2})(?:[:\-]?(\d{2}))?\b/
  }

  const dateInfo = {}
  const text = words.join(' ')

  const yearMatch = text.match(datePatterns.year)
  if (yearMatch) dateInfo.year = yearMatch[1]

  const monthMatch = text.match(datePatterns.month)
  if (monthMatch) dateInfo.month = monthMatch[1]

  return dateInfo
}

export function generateSmartName(words, extension, originalName) {
  const isAuto = isAutoGeneratedName(originalName)

  if (isAuto) {
    const timestamp = Date.now().toString(36)
    const typeHint = extension.replace('.', '').toLowerCase()
    return `${typeHint}_${timestamp}${extension}`
  }

  const dateInfo = detectDateInfo(words)

  const dateStr = dateInfo.year
    ? `${dateInfo.year}${dateInfo.month ? '_' + dateInfo.month : ''}`
    : ''

  const meaningfulWords = words.filter(w => {
    const isNumber = /^\d+$/.test(w)
    const isDate = dateInfo.year && w === dateInfo.year
    return !isNumber && !isDate && w.length > 2
  })

  if (meaningfulWords.length > 0) {
    const name = meaningfulWords.slice(0, 4).join('_')
    return dateStr ? `${name}_${dateStr}${extension}` : `${name}${extension}`
  }

  const baseName = originalName
    .replace(/\.[^.]+$/, '')
    .replace(/\([\d]+\)/g, '')
    .replace(/[_\-]+/g, ' ')
    .replace(/\d+/g, '')
    .replace(/\s+/g, ' ')
    .trim()

  if (baseName.length > 2) {
    const cleanName = baseName.replace(/[^a-zA-Z0-9 ]/g, '').trim().replace(/\s+/g, '_')
    return dateStr ? `${cleanName}_${dateStr}${extension}` : `${cleanName}${extension}`
  }

  const timestamp = Date.now().toString(36)
  return `file_${timestamp}${extension}`
}

export function generateCategory(words, extension) {
  const fromExtension = CATEGORY_MAP[extension]
  if (fromExtension) {
    for (const [category, keywords] of Object.entries(KEYWORD_CATEGORIES)) {
      if (words.some(w => keywords.includes(w))) {
        return category
      }
    }
    return fromExtension
  }

  for (const [category, keywords] of Object.entries(KEYWORD_CATEGORIES)) {
    if (words.some(w => keywords.includes(w))) {
      return category
    }
  }

  return 'Uncategorized'
}

export function generateTags(words) {
  const stopWords = ['the', 'and', 'for', 'that', 'with', 'this', 'from', 'was', 'are', 'has', 'have', 'can', 'will', 'not', 'but', 'all', 'any', 'its', 'let', 'may', 'new', 'now', 'old', 'see', 'way', 'who', 'did', 'get', 'got', 'had', 'her', 'him', 'his', 'how', 'man', 'our', 'out', 'say', 'she', 'too', 'use']

  const tags = []
  for (const word of words) {
    if (!stopWords.includes(word) && word.length > 2 && !/^\d+$/.test(word)) {
      tags.push(word)
    }
  }
  return [...new Set(tags)].slice(0, 5)
}

export function generateDescription(words, category, extension, originalName) {
  const fileType = extension.replace('.', '').toUpperCase()
  const isAuto = isAutoGeneratedName(originalName)

  if (isAuto) {
    const categoryDescriptions = {
      'Images': `${fileType} image file requiring visual analysis for content description.`,
      'Documents': `${fileType} document file. Upload and analyze to extract content details.`,
      'Screenshots': `${fileType} screenshot capture. Analyze to identify the captured content.`,
      'Videos': `${fileType} video file.`,
      'Audio': `${fileType} audio file.`
    }
    return categoryDescriptions[category] || `${fileType} file in the ${category} category.`
  }

  const meaningfulWords = words.filter(w => w.length > 2 && !/^\d+$/.test(w))

  if (meaningfulWords.length > 0) {
    const mainWords = meaningfulWords.slice(0, 4).join(' ')
    return `${fileType} file related to ${mainWords} in the ${category} category.`
  }

  const categoryDescriptions = {
    'Screenshots': `${fileType} screenshot capture.`,
    'Photos': `${fileType} photo image.`,
    'Documents': `${fileType} document file.`,
    'Code': `${fileType} source code file.`,
    'Work': `${fileType} work-related file.`,
    'Education': `${fileType} educational material.`,
    'Design': `${fileType} design file.`,
    'Finance': `${fileType} financial document.`,
    'Personal': `${fileType} personal file.`,
    'Downloads': `${fileType} downloaded file.`,
    'Images': `${fileType} image file.`,
    'Videos': `${fileType} video file.`,
    'Audio': `${fileType} audio file.`
  }

  return categoryDescriptions[category] || `${fileType} file in the ${category} category.`
}

function generateConfidence(words, extension, originalName) {
  let confidence = 0.5

  const isAuto = isAutoGeneratedName(originalName)
  if (isAuto) {
    confidence = 0.3
  } else {
    const meaningfulWords = words.filter(w => w.length > 2 && !/^\d+$/.test(w))
    if (meaningfulWords.length > 2) confidence += 0.15
    if (meaningfulWords.length > 4) confidence += 0.1
    if (words.some(w => w.length > 4)) confidence += 0.05
    if (CATEGORY_MAP[extension]) confidence += 0.05
  }

  return Math.min(Math.round((confidence + Math.random() * 0.1) * 100) / 100, 0.99)
}

async function extractPdfText(filePath) {
  try {
    const data = await readFile(filePath)
    const parser = new PDFParse({ data })
    const result = await parser.getText()
    await parser.destroy()
    const text = (result?.text || '').replace(/\s+/g, ' ').trim()
    return text.substring(0, 2000)
  } catch {
    return ''
  }
}

export function analyzePdfContent(text) {
  if (!text) {
    return {
      category: 'Documents',
      tags: ['pdf', 'document'],
      description: 'PDF document file.',
      suggestedName: null
    }
  }

  const words = parseFilename(text.substring(0, 200))
  const category = generateCategory(words, '.pdf')
  const tags = generateTags(words)

  const meaningfulWords = words.filter(w => w.length > 2 && !/^\d+$/.test(w))
  let description = ''
  let suggestedName = null

  if (meaningfulWords.length > 0) {
    const mainWords = meaningfulWords.slice(0, 5).join(' ')
    description = `PDF document containing content related to: ${mainWords}.`
    suggestedName = meaningfulWords.slice(0, 4).join('_')
  } else {
    description = 'PDF document file.'
  }

  return { category, tags, description, suggestedName }
}

function ruleBasedAnalysis(file) {
  const words = parseFilename(file.originalName)
  const category = generateCategory(words, file.extension)
  const tags = generateTags(words)
  const description = generateDescription(words, category, file.extension, file.originalName)
  const confidence = generateConfidence(words, file.extension, file.originalName)
  const generatedName = generateSmartName(words, file.extension, file.originalName)

  return {
    generatedName,
    description,
    category,
    tags,
    confidence,
    aiSource: 'rule-based'
  }
}

function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

async function callGeminiWithRetry(imageBuffer, extension, retries = 3) {
  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      console.log(`[AI] Gemini attempt ${attempt}/${retries}`)
      return await analyzeImageWithGemini(imageBuffer, extension)
    } catch (error) {
      const isRateLimit = error.message.includes('429') ||
        error.message.includes('RESOURCE_EXHAUSTED') ||
        error.message.includes('rate') ||
        error.message.includes('quota')

      console.error(`[AI] Attempt ${attempt} failed: ${error.message}`)

      if (attempt < retries) {
        const waitMs = isRateLimit ? 5000 * attempt : 2000 * attempt
        console.log(`[AI] Retrying in ${waitMs}ms...`)
        await delay(waitMs)
      } else {
        throw error
      }
    }
  }
}

export async function analyzeFile(file) {
  const isImage = IMAGE_EXTENSIONS.includes(file.extension?.toLowerCase())
  const isPdf = file.extension?.toLowerCase() === '.pdf'

  console.log(`[AI] Analyzing: ${file.originalName}, ext: ${file.extension}, isImage: ${isImage}, isPdf: ${isPdf}, hasKey: ${!!process.env.GEMINI_API_KEY}`)

  if (isImage && process.env.GEMINI_API_KEY) {
    try {
      const filePath = path.join(UPLOAD_DIR, file.filePath)
      const imageBuffer = await readFile(filePath)
      console.log(`[AI] Calling Gemini Vision for: ${filePath} (${Math.round(imageBuffer.length / 1024)}KB)`)
      const visionResult = await callGeminiWithRetry(imageBuffer, file.extension)
      console.log(`[AI] Gemini result:`, visionResult)

      const generatedName = visionResult.suggestedName
        ? `${visionResult.suggestedName.replace(/\s+/g, '_')}${file.extension}`
        : generateSmartName(parseFilename(file.originalName), file.extension, file.originalName)

      return {
        generatedName,
        description: visionResult.description || generateDescription(
          parseFilename(file.originalName),
          visionResult.category || 'Screenshots',
          file.extension,
          file.originalName
        ),
        category: visionResult.category || 'Screenshots',
        tags: visionResult.tags.length > 0 ? visionResult.tags : generateTags(parseFilename(file.originalName)),
        confidence: 0.95,
        aiSource: 'gemini-vision',
        visionData: {
          appName: visionResult.appName,
          content: visionResult.content
        }
      }
    } catch (error) {
      console.error('[AI] Gemini vision FAILED after retries:', error.message)
      console.error('[AI] Falling back to rule-based analysis')
      return ruleBasedAnalysis(file)
    }
  }

  if (isPdf && process.env.GEMINI_API_KEY) {
    try {
      const filePath = path.join(UPLOAD_DIR, file.filePath)
      const pdfBuffer = await readFile(filePath)
      console.log(`[AI] Calling Gemini Vision for PDF: ${filePath} (${Math.round(pdfBuffer.length / 1024)}KB)`)
      const pdfResult = await analyzePdfWithGemini(pdfBuffer)
      console.log(`[AI] Gemini PDF result:`, pdfResult)

      const generatedName = pdfResult.suggestedName
        ? `${pdfResult.suggestedName.replace(/\s+/g, '_')}${file.extension}`
        : generateSmartName(parseFilename(file.originalName), file.extension, file.originalName)

      return {
        generatedName,
        description: pdfResult.description || generateDescription(
          parseFilename(file.originalName),
          pdfResult.category || 'Documents',
          file.extension,
          file.originalName
        ),
        category: pdfResult.category || 'Documents',
        tags: pdfResult.tags.length > 0 ? pdfResult.tags : generateTags(parseFilename(file.originalName)),
        confidence: 0.95,
        aiSource: 'gemini-vision',
        visionData: {
          appName: '',
          content: pdfResult.content.substring(0, 1000)
        }
      }
    } catch (error) {
      console.error('[AI] Gemini PDF analysis FAILED:', error.message)
      console.error('[AI] Falling back to PDF text extraction')
    }
  }

  if (isPdf) {
    try {
      const filePath = path.join(UPLOAD_DIR, file.filePath)
      console.log(`[AI] Extracting PDF text from: ${filePath}`)
      const pdfText = await extractPdfText(filePath)

      if (pdfText) {
        console.log(`[AI] PDF text extracted (${pdfText.length} chars)`)
        const pdfAnalysis = analyzePdfContent(pdfText)

        const generatedName = pdfAnalysis.suggestedName
          ? `${pdfAnalysis.suggestedName}${file.extension}`
          : generateSmartName(parseFilename(file.originalName), file.extension, file.originalName)

        return {
          generatedName,
          description: pdfAnalysis.description,
          category: pdfAnalysis.category,
          tags: pdfAnalysis.tags,
          confidence: 0.85,
          aiSource: 'pdf-extraction',
          visionData: {
            appName: '',
            content: pdfText.substring(0, 1000)
          }
        }
      }
    } catch (error) {
      console.error('[AI] PDF extraction failed:', error.message)
    }
  }

  console.log('[AI] Using rule-based analysis')
  return ruleBasedAnalysis(file)
}
